---

- name: install open jdk 1.8
  yum:
    name: "{{ install_pkg }}"
    state: present

- name: create user "app" and home dir will /opt/app and its a /bin/nologin
  user:
    name: "{{ user_name }}"
    comment: "{{ user_name }}"
    home: "{{ user_home }}"
    shell: /bin/nologin
    state: present

- name: crete group app
  group: 
    name: "{{ group_name }}"
    state: present

- name: Create a app directory if it does not exist
  file:
    path: /opt/app/tomcat
    state: directory
    mode: '0755'
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Download tomcat tar.gz file from internet
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt
    mode: '0440'

- name: Unarchive tomcat tar file that is already on the remote machine
  unarchive:
    src: "/opt/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt/app/tomcat
    remote_src: yes

- name: Recursively change ownership of a directory
  file:
    path: "{{ user_home }}"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: copy tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "/opt/app/tomcat/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: '0644'
  notify: restart tomcat

- name: copy context.xml
  template:
    src: context.xml.j2
    dest: /opt/app/tomcat/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: '0644'
  notify: restart tomcat

- name: copy tomcat service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0755'
  notify: restart tomcat


- name: Start and enable tomcat service
  service:
    name: tomcat
    state: started
    enabled: yes
